export enum CitizenStatus {
  CITIZEN_OF_US = 1,
  NON_CITIZEN_OF_US,
  LAWFUL_PERMANENT_CITIZEN,
  ALIEN_AUTHORIZE_TO_WORK_UNTIL,
  
}

export enum CitizenChildStatus {
  ALIEN_REGISTRATION_NUMBER = 1,
  FORM_ADMISSION_NUMBER,
  FOREIGN_PASSPORT_NUMBER
}