export enum FormField {
    TaxWithholdingInfoSummary = 1,
    TaxWithholdingInfoEmployer = 2,
    TaxWithholdingInfoEmployee = 3,
    TaxWithholdingInfoQuickHire = 4,
    I9QuickHire = 5,
    I9Summary = 6,
    I9Employer = 7,
    I9Employee = 8,
    EEOEmployee = 9,
    EEOOnboard = 10,
    EEOQuickHire = 11,
    VEVRAAEmployee = 12,
    VEVRAAHrm = 13,
    VEVRAAQuickHire = 14,
    WOTCOnboardSummary = 15,
    WOTC8850Employee = 16,
    WOTC8850Employer = 17,
    WOTC9061Employee = 18,
    WOTC9061Employer = 19,
    WOTC9062 = 20,
    WOTCQuickHire = 21,
    TaxWithholdingInfoHR = 22,
    Vacation = 23,
    EmploymentInformation = 24,
    PayrollInformation = 25
}