import { IUIFieldCustomizationMap } from '@/models/UIFieldCustomizationMap';
import { UIFieldMapForAddress } from '@/models/UIFieldMapForAddress';
import { UIFunctions } from '@/enums/UIFunctions';

export default class UIFieldStore {

    public static getUIFunctionIdFromPageType(pageType: string): number {
        const uiFunctionMap: { [key: string]: number } = {
            projects: 33,
            rfis: 36,
            companies: 39,
            people: 41,
            submittals: 60,
            rfcs: 110,
            changeorders: 118,
            actionitems: 122,
            'user defined documents': 120,
            purchaseorders: 124,
            subcontracts: 152,
            punchlists: 161,
            tasks: 163,
            'aia general': 222,
            'aia signature': 224,
        };

        return uiFunctionMap[pageType.toLowerCase()] || 0;
    }

    public uiFields: IUIFieldCustomizationMap = {};

    public uiAddressFieldMap: {
        [uiFunction in UIFunctions]: UIFieldMapForAddress
    } = {
            [UIFunctions.Project]: {
                address1Label: 'PM_33_1173',
                address1: 'PM_33_1174',
                address2Label: 'PM_33_1434',
                address2: 'PM_33_1435',
                cityLabel: 'PM_33_1436',
                city: 'PM_33_1437',
                stateLabel: 'PM_33_1438',
                state: 'PM_33_1439',
                zipCodeLabel: 'PM_33_1440',
                zipCode: 'PM_33_1441',
                countryLabel: 'PM_33_1442',
                country: 'PM_33_1443',
            },
            [UIFunctions.Company]: {
                address1Label: 'PM_39_1273',
                address1: 'PM_39_1274',
                address2Label: 'PM_39_1536',
                address2: 'PM_39_1275',
                cityLabel: 'PM_39_1276',
                city: 'PM_39_1277',
                stateLabel: 'PM_39_1278',
                state: 'PM_39_1279',
                zipCodeLabel: 'PM_39_1280',
                zipCode: 'PM_39_1281',
                countryLabel: 'PM_39_1282',
                country: 'PM_39_1283',
            },
            [UIFunctions.Person]: {
                address1Label: 'PM_41_1308',
                address1: 'PM_41_1309',
                address2Label: 'PM_41_1545',
                address2: 'PM_41_1310',
                cityLabel: 'PM_41_1311',
                city: 'PM_41_1312',
                stateLabel: 'PM_41_1313',
                state: 'PM_41_1314',
                zipCodeLabel: 'PM_41_1315',
                zipCode: 'PM_41_1316',
                countryLabel: 'PM_41_1317',
                country: 'PM_41_1318',
            },
            [UIFunctions.Submittal]: null,
            [UIFunctions.Correspondence]: null,
            [UIFunctions.RFI]: null,
            [UIFunctions.UserDefinedDocument]: null,
            [UIFunctions.CompanyCreateModal]: null,
            [UIFunctions.CompanyDetails]: null,
            [UIFunctions.PersonCreateModal]: null,
            [UIFunctions.PersonDetails]: null,
            [UIFunctions.Setup]: null,
            [UIFunctions.ProjectDetails]: null,
            [UIFunctions.RecycleBin]: null,
            [UIFunctions.User]: null,
            [UIFunctions.ProjectBudgetAddPanel]: null,
            [UIFunctions.RFC]: null,
            [UIFunctions.ChangeOrder]: null,
            [UIFunctions.ActionItem]: null,
            [UIFunctions.PunchList]: null,
            [UIFunctions.PurchaseOrder]: {
                address1Label: 'PM_124_2334',
                address1: 'PM_124_2334',
                address2Label: 'PM_124_2465',
                address2: 'PM_124_2465',
                cityLabel: 'PM_124_2466',
                city: 'PM_124_2466',
                stateLabel: 'PM_124_2467',
                state: 'PM_124_2467',
                zipCodeLabel: 'PM_124_2468',
                zipCode: 'PM_124_2468',
                countryLabel: 'PM_124_2469',
                country: 'PM_124_2469',
            },
            [UIFunctions.PhotoLog]: null,
            [UIFunctions.Subcontract]: null,
            [UIFunctions.PunchList]: null,
            [UIFunctions.ChangeOrderDetailReport]: null,
            [UIFunctions.ChangeOrderLogReport]: null,
            [UIFunctions.ChangeOrderVarianceReport]: null,
            [UIFunctions.CommittedCostVarianceReport]: null,
            [UIFunctions.CompanyListReport]: null,
            [UIFunctions.PersonListReport]: null,
            [UIFunctions.DailyLogSummaryReport]: null,
            [UIFunctions.DelayLogReport]: null,
            [UIFunctions.EquipmentLogReport]: null,
            [UIFunctions.LaborLogReport]: null,
            [UIFunctions.ManpowerLogReport]: null,
            [UIFunctions.MaterialLogReport]: null,
            [UIFunctions.VisitorLogReport]: null,
            [UIFunctions.WeatherLogReport]: null,
            [UIFunctions.CostItemReport]: null,
            [UIFunctions.ActionItemListReport]: null,
            [UIFunctions.ProjectListReport]: null,
            [UIFunctions.ProjectListDetailedReport]: null,
            [UIFunctions.UserDefinedDocumentListReport]: null,
            [UIFunctions.RFCDetailReport]: null,
            [UIFunctions.RFCLogReport]: null,
            [UIFunctions.RFIDetailReport]: null,
            [UIFunctions.RFILogReport]: null,
            [UIFunctions.RFISummaryReport]: null,
            [UIFunctions.SubmittalDetailReport]: null,
            [UIFunctions.SubmittalLogReport]: null,
            [UIFunctions.SubmittalSummaryReport]: null,
            [UIFunctions.PurchaseOrderLogReport]: null,
            [UIFunctions.PurchaseOrderDetailReport]: null,
            [UIFunctions.Subcontract]: null,
            [UIFunctions.ScheduleSummaryReport]: null,
            [UIFunctions.ScheduleDetailReport]: null,
            [UIFunctions.SubcontractLogReport]: null,
            [UIFunctions.PunchList]: null,
            [UIFunctions.SubcontractDetailReport]: null,
            [UIFunctions.PunchListLogReport]: null,
            [UIFunctions.PurchaseOrderChangeOrder]: null,
            [UIFunctions.PunchListDetailReport]: null,
            [UIFunctions.SubcontractChangeOrder]: null,
            [UIFunctions.PurchaseOrderChangeOrderDetailReport]: null,
            [UIFunctions.SubcontractChangeOrderDetailReport]: null,
            [UIFunctions.AiaGeneral]: {
                address1Label: 'PM_222_2951',
                address1: 'PM_222_2952',
                address2Label: 'PM_222_2953',
                address2: 'PM_222_2954',
                cityLabel: 'PM_222_2955',
                city: 'PM_222_2956',
                stateLabel: 'PM_222_2957',
                state: 'PM_222_2958',
                zipCodeLabel: 'PM_222_2959',
                zipCode: 'PM_222_2960',
                countryLabel: 'PM_222_2961',
                country: 'PM_222_2962',
            },
            [UIFunctions.AiaSignature]: {
                address1Label: 'PM_224_2981',
                address1: 'PM_224_2982',
                address2Label: 'PM_224_2983',
                address2: 'PM_224_2984',
                cityLabel: 'PM_224_2985',
                city: 'PM_224_2986',
                stateLabel: 'PM_224_2987',
                state: 'PM_224_2988',
                zipCodeLabel: 'PM_224_2989',
                zipCode: 'PM_224_2990',
                countryLabel: 'PM_224_2991',
                country: 'PM_224_2992',
            },
            [UIFunctions.AiaBillingReport]: null,
            [UIFunctions.SubmittedTimeReport]: null,
            [UIFunctions.BreakTrackingReport]: null
        };

    public isRequired(uiFieldTag: string): boolean {
        return !!(this.uiFields[uiFieldTag] && this.uiFields[uiFieldTag].required);
    }
}
